/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author nxnam
 */
public class panel_QuanLyKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form Panel_QuanLyKhachHang
     */
    public panel_QuanLyKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_tieuDe = new javax.swing.JPanel();
        lbl_TieuDe = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        paneKhachHang = new javax.swing.JScrollPane();
        tableKhachHang = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new java.awt.BorderLayout());

        pnl_tieuDe.setBackground(new java.awt.Color(0, 255, 255));
        pnl_tieuDe.setPreferredSize(new java.awt.Dimension(1000, 50));
        pnl_tieuDe.setLayout(new java.awt.BorderLayout());

        lbl_TieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_TieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe.setText("QUẢN LÍ KHÁCH HÀNG");
        pnl_tieuDe.add(lbl_TieuDe, java.awt.BorderLayout.CENTER);

        add(pnl_tieuDe, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());
        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 450));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel2.setLayout(new java.awt.BorderLayout());

        tableKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        paneKhachHang.setViewportView(tableKhachHang);

        jPanel2.add(paneKhachHang, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_TieuDe;
    private javax.swing.JScrollPane paneKhachHang;
    private javax.swing.JPanel pnl_tieuDe;
    private javax.swing.JTable tableKhachHang;
    // End of variables declaration//GEN-END:variables
}
